foodganizer/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'))
]

website/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views
from . import api_endpoints

urlpatterns = [
    path('', views.index, name='index'),
    path('signup', views.signup, name='signup'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('profile', views.profile, name='profile'),
    path('profile/<slug:username>', views.view_profile, name='otherprofile'),
    path('quaggatest', views.quaggatest, name='quaggatest'),
    path('logout', auth_views.LogoutView.as_view(
        extra_context={
            'next': '/',
        },
    ), name='logout'),
    path('kitchens', views.kitchens, name='kitchens'),
    path('kitchens/new', views.new_kitchen, name='new_kitchen'),
    path('kitchens/share/<uuid:share_uuid>', views.shared_kitchen, name='share_kitchen_link'),
    path('kitchens/<int:id>', views.kitchen, name='kitchen'),
    path('kitchens/<int:id>/invite', views.invite_users, name='kitchen_invite_users'),
    path('memberships/<int:id>/delete', views.delete_membership, name='delete_membership'),
    path('memberships/<int:id>/promote', views.promote_membership, name='promote_membership'),
    path('kitchens/<int:id>/share', views.set_kitchen_sharing, name='set_kitchen_sharing'),
    path('kitchens/<int:id>/join', views.join_kitchen, name='join_kitchen'),

    path('kitchens/<int:id>/stored/add', views.add_storeditem_kitchen, name='add_storeditem_kitchen'),
    path('kitchens/<int:id>/stored/delete', views.delete_storeditem_kitchen, name='delete_storeditem_kitchen'),
    path('kitchens/<int:id>/stored/update/<int:item_id>', views.update_storeditem_kitchen, name='update_storeditem_kitchen'),
    path('kitchens/<int:id>/stored/move/<int:item_id>', views.move_storeditem_kitchen, name='move_storeditem_kitchen'),

    path('kitchens/<int:id>/cart/add', views.add_cartitem_kitchen, name='add_cartitem_kitchen'),
    path('kitchens/<int:id>/cart/update/<int:item_id>', views.update_cartitem_kitchen, name='update_cartitem_kitchen'),
    path('kitchens/<int:id>/cart/delete/<int:item_id>', views.delete_cartitem_kitchen, name='delete_cartitem_kitchen'),
    path('kitchens/<int:id>/cart/move/<int:item_id>', views.move_cartitem_kitchen, name='move_cartitem_kitchen'),

    path('kitchens/<int:id>/new', views.new_kitchen_item, name='new_kitchen_item'),
    path('kitchens/<int:id>/custom/delete/<int:item_id>', views.delete_customitem_kitchen, name='delete_customitem_kitchen'),

    path('kitchens/<int:id>/postit/new', views.create_postit, name='create_postit'),
    path('kitchens/<int:id>/postit/edit/<int:postit_id>', views.edit_postit, name='edit_postit'),
    path('kitchens/<int:id>/postit/delete/<int:postit_id>', views.delete_postit, name='delete_postit'),

    path('api/products/search', api_endpoints.search_products, name='search_products_api'),
    path('api/product/search', api_endpoints.get_product_by_code, name='check_product_exists_api')

]

website/models.py
import json
from django.core.exceptions import ObjectDoesNotExist

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.fields.related import ForeignKey, ManyToManyField


def _getLastUpdate():
    return models.DateTimeField(auto_now=True)
    
def _getCreatedAt():
    return models.DateTimeField(auto_now_add=True)

def _getProductQuantity():
    # from 0 to 32767 https://docs.djangoproject.com/en/3.2/ref/models/fields/#positivesmallintegerfield
    return  models.PositiveSmallIntegerField(null=True, default=None) 

def _getAddedBy():
    return models.ForeignKey('User', on_delete=models.SET_NULL, null=True)

def _getLastEditedBy(related_name=None):
    return models.ForeignKey('User', on_delete=models.SET_NULL, null=True, related_name=related_name)

def _getKitchenForeignKey():
    return models.ForeignKey('Kitchen', on_delete=models.CASCADE)  # class Kitchen is not defined yet, must use a string

def _getItemForeignKey():
    return models.ForeignKey('Item', on_delete=models.PROTECT)  # class Kitchen is not defined yet, must use a string


class User(AbstractUser):
    bio = models.TextField(max_length=1000, blank=True)
    profile_pic = models.ImageField(upload_to='profile_images', blank=True)



class Item(models.Model):
    upc = models.CharField(max_length=13, blank=True)
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=500, blank=True)
    image = models.ImageField(upload_to='item_images', blank=True)
    added_by = _getAddedBy()
    last_update = _getLastUpdate()
    created_at = _getCreatedAt()
    custom_item_kitchen = models.ForeignKey('Kitchen', on_delete=models.CASCADE, null=True, default=None) 

    def __str__(self):
        name = self.title
        if self.upc and self.upc not in ["undefined", ""]:
            name = f"{name} (UPC: {self.upc})"
        return name
 

class StoredItem(models.Model):
    item = _getItemForeignKey()
    kitchen = _getKitchenForeignKey()
    added_by = _getAddedBy()
    last_update = _getLastUpdate()
    created_at = _getCreatedAt()
    quantity = _getProductQuantity()
    expiry_date = models.DateField(null=True, default=None, blank=True)
    note = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return f"{self.item}"

    def toJSON(self):
        return json.dumps(self, default=lambda o: o.__dict__,
                          sort_keys=True, indent=4)


class Kitchen(models.Model):
    name = models.CharField(max_length=255)
    # need related_name for backward link https://stackoverflow.com/questions/2606194/django-error-message-add-a-related-name-argument-to-the-definition/44398542
    users = ManyToManyField(User, through='Membership', through_fields=('kitchen', 'user'))
    stored_items = ManyToManyField(Item, through='StoredItem', blank=True)
    public_access_uuid = models.UUIDField(null=True, default=None)
    join_confirmation = models.BooleanField(default=False)
    background_image = models.ImageField(upload_to='backgrounds', blank=True)

    def __str__(self):
        return self.name


class MembershipStatus(models.TextChoices):
    PENDING_JOIN_REQUEST = 'PENDING_JOIN_REQUEST'
    PENDING_INVITATION = 'PENDING_INVITATION'
    ACTIVE_MEMBERSHIP = 'ACTIVE_MEMBERSHIP'
    ADMIN = "ADMIN"


class Membership(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    kitchen = _getKitchenForeignKey()
    status = models.CharField(
        max_length=30,
        choices=MembershipStatus.choices
    )
    invited_by = models.ForeignKey(User, on_delete=models.SET_NULL, default=None, null=True, related_name="invites_set")

    def __str__(self):
        if self.status == MembershipStatus.PENDING_INVITATION:
            message = f"@{self.invited_by} invited @{self.user} in {self.kitchen}" 
        elif self.status == MembershipStatus.PENDING_JOIN_REQUEST:
            message = f"@{self.user} requested to join {self.kitchen}" 
        elif self.status == MembershipStatus.ACTIVE_MEMBERSHIP:
            message = f"@{self.user} member of {self.kitchen}" 
        elif self.status == MembershipStatus.ADMIN:
            message = f"@{self.user} admin of {self.kitchen}" 
        else:
            message = f"@{self.user} > {self.status} > {self.kitchen}" 

        return message

    class Meta:
        unique_together = [['user', 'kitchen']]
        

class PostIt(models.Model):
    text = models.TextField(max_length=1000)
    author = _getAddedBy()
    last_edited_by = _getLastEditedBy('+')
    kitchen = _getKitchenForeignKey()
    last_update = _getLastUpdate()
    created_at = _getCreatedAt()


class ShoppingCartItem(models.Model):
    kitchen = _getKitchenForeignKey()
    item = _getItemForeignKey()
    added_by = _getAddedBy()
    quantity = _getProductQuantity()
    last_update = _getLastUpdate()
    created_at = _getCreatedAt()

    def __str__(self):
        return f"{self.quantity}x {self.item}"

website/forms.py
from crispy_forms.bootstrap import PrependedText
from crispy_forms.helper import FormHelper
from django.forms.fields import BooleanField
from crispy_forms.layout import Field, Layout, HTML, Button

from .models import Item, Kitchen, User, StoredItem, PostIt, ShoppingCartItem
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import validate_email
from django.core.exceptions import ValidationError


## CUSTOM FIELDS ##

class MultiUserField(forms.Field):
    def to_python(self, value):
        if not value:
            return []
        
        contacts = value.replace(";", " ").replace(",", " ").split()
        users = []
        data = []
        for c in contacts:
            try:
                validate_email(c)
                try:
                    u = User.objects.get(email=c)
                except User.DoesNotExist:
                    u = None
                if u not in users or u is None:
                    users.append(u)
                    data.append({"value": c, "is_email": True, "User": u})
            except ValidationError:
                try:                            
                    u = User.objects.get(username=c)
                except User.DoesNotExist:                
                    u = None                                
                if c.startswith('@'):
                    c = c[1:]
                if u not in users or u is None:
                    users.append(u)    
                    data.append({"value": c, "is_email": False, "User": u})
        return data

    def validate(self, value):
        if isinstance(value, list) and len(value) == 0:
            return # an empty array is ok
        super().validate(value)
        incorrect_emails = []
        incorrect_usernames = []
        for c in value:
            if not c["User"]:
                if c["is_email"]:
                    incorrect_emails.append(c["value"])
                else:
                    incorrect_usernames.append(c["value"])
                
        error_messages = []

        for ie in incorrect_emails:
            error_messages.append(f"{ie}: We couldn't find a user with this email address")
        
        for iu in incorrect_usernames:
            error_messages.append(f"@{iu}: We couldn't find a user with this username")

        if error_messages:
            raise ValidationError("\n".join(error_messages))


## FORMS ##

class UpdateUserForm(ModelForm):
    email = forms.EmailField(required=False)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'bio', 'profile_pic']


class UserRegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            PrependedText('username', text='@'),
            Field('email'),
            Field('password1', placeholder="Password"),
            Field('password2', placeholder="Password confirmation"),
            Button('submit', 'Sign up', css_class='btn btn-success w-100')
        )

    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class NewKitchenForm(ModelForm):
    invite_other_users = MultiUserField(widget=forms.Textarea, required=False)

    class Meta:
        model = Kitchen
        fields = ['name', 'invite_other_users']


class UpdateKitchenForm(ModelForm):
    background_image = forms.ImageField(required=False)

    class Meta:
        model = Kitchen
        fields = ['name', 'background_image']


class NewKitchenItemForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(NewKitchenItemForm, self).__init__(*args, **kwargs)
        self.fields['upc'].label = "EAN-13 / UPC"
        self.fields['upc'].max_length = 13


    upc = forms.CharField(max_length=13, min_length=12, required=False)
    image = forms.ImageField(required=False)

    class Meta:
        model = Item
        widgets = {
            'upc': forms.TextInput(attrs={
                'size': 13,
                'maxlength': 13
            })
        }
        fields = ['upc', 'title', 'description', 'image']


class AddStoredItemForm(ModelForm):
    Field('item', type="hidden")

    class Meta:
        model = StoredItem
        widgets = {
            'expiry_date': forms.DateInput(attrs={'type': 'date'}),
            'item': forms.HiddenInput()
        }
        fields = ['item', 'quantity', 'expiry_date', 'note']


class AddShoppingCartItemForm(ModelForm):
    Field('item', type="hidden")

    class Meta:
        model = ShoppingCartItem
        exclude = ['added_by', 'kitchen']
        widgets = {
            'item': forms.HiddenInput()
        }


class UpdateShoppingCartItemForm(ModelForm):
    class Meta:
        model = ShoppingCartItem
        fields = ['quantity']


class RemoveStoredItemForm(forms.Form):
    def __init__(self, *args, **kwargs):
        item_set = kwargs.pop('item_set')
        super(RemoveStoredItemForm, self).__init__(*args, **kwargs)
        self.fields['item'].queryset = item_set

    Field('item', type="hidden")

    item = forms.ModelChoiceField(queryset=None, required=True)
    add_to_shopping_list = forms.BooleanField(required=False)


class UpdateStoredItemForm(ModelForm):
    Field('quantity', type="hidden")

    class Meta:
        model = StoredItem
        widgets = {
            'expiry_date': forms.DateInput(attrs={'type': 'date'}),
            'quantity': forms.TextInput(attrs={'min': 1, 'type': 'number'})    # forms.NumberInput(attrs={'min': 1})
        }
        fields = ['quantity', 'note', 'expiry_date']


class InviteExistingUsers(forms.Form):
    invite_other_users = MultiUserField(widget=forms.Textarea, required=False)


class ShareKitchenForm(forms.Form):
    enable_kitchen_sharing_link = BooleanField(required=False)
    join_confirmation_needed = BooleanField(required=False)


class NewPostItForm(ModelForm):
    class Meta:
        model = PostIt
        fields = ['text']

website/templates/components/kitchen-forms/confirmationModal.html
{% load crispy_forms_tags %}

<div class="modal fade" id="confirmationModal" tabindex="-1" aria-labelledby="itemInfoModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <form novalidate>
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body overflow-hidden pb-2">
                </div>
                <div class="modal-footer row d-flex justify-content-center">
                    <button type="button" data-bs-dismiss="modal" data-bs-toggle="modal" class="modal-cancel-button btn btn-outline-secondary col-5 cancel-button">Cancel</button>
                    <button type="submit" class="btn col-5 confirm-button"></button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    const confirmationModal = $$("#confirmationModal")
    const baseConfirmButtonClasses = confirmationModal.querySelector(".confirm-button").className

    function addConfirmationModal(entry) {
        entry.addEventListener("click", _ => {
            confirmationModal.querySelector(".modal-title").textContent = entry.dataset.modalTitle
            confirmationModal.querySelector(".modal-body").textContent = entry.dataset.modalBody
            confirmationModal.querySelector(".confirm-button").className = baseConfirmButtonClasses
            if (entry.dataset.modalConfirmClasses) {
                confirmationModal.querySelector(".confirm-button").classList.add(...(entry.dataset.modalConfirmClasses.split(" ")))
            }
            confirmationModal.querySelector(".confirm-button").textContent = entry.dataset.modalConfirmCta
            confirmationModal.querySelector("form").action = entry.dataset.action 
            confirmationModal.querySelector("form").method = "POST"

            confirmationModal.querySelector(".modal-cancel-button").dataset.bsTarget = entry.dataset.backBsTarget

            if (entry.dataset.modalConfirmCtaIconClass) {
                // if modalConfirmCtaIconClass = "bi bi-star-fill" append <i class="bi bi-star-fill"></i> tag in the confirm button
                let icon = document.createElement("i")
                icon.classList.add(...(entry.dataset.modalConfirmCtaIconClass.split(" ")), "ms-1")
                confirmationModal.querySelector(".confirm-button").appendChild(icon)
            }
            
            bootstrap.Modal.getOrCreateInstance(confirmationModal).show()
        })
    } 
</script>

website/templates/components/kitchen-forms/edit-cartitem-modal.html
{% load crispy_forms_tags %}

<div class="modal fade" id="cartItemEditModal" tabindex="-1" aria-labelledby="cartItemEditModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <form novalidate method="POST">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Cart item "<b class="item-name"></b>"</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="text-muted mb-3">
                        <p class="text-muted fst-italic mb-0" id="item-desc"></p>
                        &ndash;&nbsp;<a class="fst-italic" id="item-added-by" href="/profile"></a>
                    </div>
                    {{ form|crispy }}
                </div>
                <div class="modal-footer d-flex">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal" data-bs-toggle="modal" data-bs-target="#removeCartItemModal"><i class="bi bi-trash-fill flex-grow-0"></i></button>
                    <button type="button" class="btn btn-warning flex-grow-0 moveToButton" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true" title="You can also use <code>i</code>"><i class="bi bi-cart-plus-fill flex-grow-0"></i>&nbsp;Move to stored items</button>
                    <button type="submit" class="btn btn-success flex-grow-1">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="removeCartItemModal" tabindex="-1" aria-labelledby="removeCartItemModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <form method="GET" action="" novalidate>
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Delete item?</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body overflow-hidden">
                    <div>Are you sure you want to delete <b class="item-name"></b>?</div>
                </div>
                <div class="modal-footer d-flex-grow-1-child">
                    <button type="button" data-bs-dismiss="modal" data-bs-toggle="modal" data-bs-target="#cartItemEditModal" class="btn btn-outline-secondary">Do not delete</button>
                    <button type="submit" class="btn btn-danger"><i class="bi bi-trash-fill"></i>&nbsp;&nbsp;Remove</button>
                </div>
            </form>
        </div>
    </div>
</div>

website/templates/components/kitchen-forms/edit-kitchen-modal.html
{% load crispy_forms_tags %}

<div class="modal fade" id="editKitchenModal" tabindex="-1" aria-labelledby="editKitchenModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <form novalidate method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Edit kitchen {{ k.name }}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {{ form|crispy }}
                    <div class="text-muted">
                        No background? No worries! Grab one from <a href="https://www.pexels.com/search/background" target="_blank">https://www.pexels.com/search/background</a>
                    </div>
                </div>
                <div class="modal-footer d-flex">
                    <button type="button" class="btn btn-secondary flex-grow-0">Cancel</button>
                    <button type="submit" class="btn btn-success flex-grow-1">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>

website/templates/components/kitchen-forms/invite-users-modal.html
{% load crispy_forms_tags %}

<div class="modal fade" id="inviteUsersModal" tabindex="-1" aria-labelledby="inviteUsersModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content bg-transparent border-0">
            <div class="modal-content">
                <form autocomplete="off" method="POST" action="{% url 'kitchen_invite_users' id=kitchen.id %}" novalidate>
                    <input autocomplete="false" name="hidden" type="text" class="invisible" style="position: absolute;">
                    <div class="modal-header">
                        <h5 class="modal-title">Invite friends</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        {% csrf_token %}
                        <fieldset class="form-group">  
                            {% comment %} <label for="{{ invite_users_form.invite_other_users.name }}" class="form-label  mt-4 mb-2"></label> {% endcomment %}
                            <div class="form-text mt-0 mb-2">Add friends by their username or e-mail address (they must already be registered on this platform)</div>   
                            {% include "components/invite-friends-to-kitchen.html" with invite_othe_users_form=invite_users_form %}
                        </fieldset>
                    </div>
                    <div class="modal-footer d-flex-grow-1-child border-0 border-bottom">
                        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Back</button>
                        <button type="submit" class="btn btn-success" id="codeNotFoundModalSuccessButton">Invite</button>
                    </div>
                </form>
            </div>
            <div class="modal-header bg-transparent border-0"></div>
            <div class="modal-content">
                <form id="set_kitchen_sharing_form" method="POST" action="{% url 'set_kitchen_sharing' id=kitchen.id %}" novalidate class="needs-validation mt-20">
                    <div class="modal-header">
                        <h5 class="modal-title">Share link</h5>
                    </div>
                    <div class="modal-body mt-3 py-0">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            {{ share_kitchen_form|crispy }}
                        </fieldset>
                        {% if kitchen.public_access_uuid %}
                        <a href="{{ share_kitchen_url }}">{{ share_kitchen_url }}</a>
                        {% endif %}
                    </div>
                    <div class="modal-footer d-flex-grow-1-child border-0 border-bottom">
                        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Back</button>
                        <button type="submit" class="btn btn-success" id="codeNotFoundModalSuccessButton">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script> 
    $$('#inviteUsersModal').addEventListener('hidden.bs.modal', function (e) {
        $$('#set_kitchen_sharing_form').reset()
    })
</script>

website/templates/components/kitchen-forms/item-info-modal.html
{% load crispy_forms_tags %}

<div class="modal fade" id="itemInfoModal" tabindex="-1" aria-labelledby="itemInfoModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <form novalidate method="POST" class="needs-validation">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title" id="item-name">Item info</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="text-muted mb-3">
                        <p class="text-muted fst-italic mb-0" id="item-desc"></p>
                        &ndash;&nbsp;<a class="fst-italic" id="item-added-by" href="/profile"></a>
                    </div>
                    {{ update_item_form|crispy }}
                </div>
                <div class="modal-footer d-flex">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal" data-bs-toggle="modal" data-bs-target="#removeItemModal"><i class="bi bi-trash-fill flex-grow-0"></i></button>
                    <button type="button" class="btn btn-warning flex-grow-0 moveToButton" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true" title="You can also press <code>c</code>"><i class="bi bi-cart-plus-fill flex-grow-0"></i>&nbsp;Move to cart</button>
                    <button type="submit" class="btn btn-success flex-grow-1">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% comment %}
    <label for="id_quantity" class="form-label mt-3">Quantity</label>
    <input required type="number" class="form-control" id="id_quantity" min="0" oninput="validity.valid||(value='');" />

    <label for="id_note" class="form-label mt-3">Note</label>
    <textarea type="text" class="form-control fst-italic" id="id_note"></textarea>
{% endcomment %}

website/templates/components/kitchen-forms/newedit-postit-modal.html
{% load crispy_forms_tags %}

<div class="modal fade" id="newPostitModal" tabindex="-1" aria-labelledby="newPostitModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <form method="POST" action="{% url "create_postit" id=id %}" novalidate class="needs-validation">
                <div class="modal-header">
                    <h5 class="modal-title">Create Post-It</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        {{ new_postit_form|crispy }}
                    </fieldset>
                </div>
                <div class="modal-footer d-flex">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal" data-bs-toggle="modal" data-bs-target="#removePostitModal"><i class="bi bi-trash-fill flex-grow-0"></i></button>
                    <button type="button" class="btn btn-outline-secondary flex-grow-1" data-bs-dismiss="modal">Back</button>
                    <button type="submit" class="btn btn-success flex-grow-1">Create</button>
                </div>
            </form>
        </div>
    </div>
</div>

website/templates/components/kitchen-forms/remove-item-modal.html
{% load crispy_forms_tags %}

<div class="modal fade" id="removeItemModal" tabindex="-1" aria-labelledby="itemInfoModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <form
                method="{% if remove_item_form %}POST{% else %}GET{% endif %}"
                action="{% if remove_item_form %}
                    {% url "delete_storeditem_kitchen" id=id %}
                {% endif %}"
                novalidate
            >
                {% if not remove_item_form %}
                    <input type="hidden" name="next" value="{{ request.path }}" />
                {% endif %}
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title" id="item-name">Delete item?</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body pb-0 overflow-hidden">
                    <div class="mb-2">Are you sure you want to delete <b id="item-name"></b>?</div>
                    {% if remove_item_form %}
                        {{ remove_item_form|crispy }}
                    {% endif %}
                </div>
                <div class="modal-footer d-flex-grow-1-child">
                    <button type="button" data-bs-dismiss="modal" data-bs-toggle="modal" data-bs-target="#itemInfoModal" class="btn btn-outline-secondary">Do not delete</button>
                    <button type="submit" class="btn btn-danger"><i class="bi bi-trash-fill"></i>&nbsp;&nbsp;Remove</button>
                </div>
            </form>
        </div>
    </div>
</div>

website/templates/components/kitchen-forms/remove-postit-modal.html
{% load crispy_forms_tags %}

<div class="modal fade" id="removePostitModal" tabindex="-1" aria-labelledby="itemInfoModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <form method="POST" action="" novalidate>
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title" id="item-name">Delete item?</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body overflow-hidden">
                    <div class="mb-2">Are you sure you want to delete the <b>Post-It</b>?</div>
                </div>
                <div class="modal-footer d-flex-grow-1-child">
                    <button type="button" data-bs-dismiss="modal" data-bs-toggle="modal" data-bs-target="#newPostitModal" class="btn btn-outline-secondary">Do not delete</button>
                    <button type="submit" class="btn btn-danger"><i class="bi bi-trash-fill"></i>&nbsp;&nbsp;Delete</button>
                </div>
            </form>
        </div>
    </div>
</div>